# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Create release and publish npm package

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org/
                  scope: "@quatico"

            - name: install
              run: pnpm install --frozen-lockfile

            - name: lint
              run: pnpm lint

            - name: test
              run: pnpm test

            - name: build
              run: pnpm build

            - name: E2E tests
              run: pnpm test:e2e

            - name: Extract release notes
              id: extract-release-notes
              uses: ffurrer2/extract-release-notes@v2
              with:
                  changelog_file: Release-Notes.md

            - name: create release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  body: ${{ steps.extract-release-notes.outputs.release_notes }}
              env:
                  # The workflow permissions of the project must be updated to 'Workflows have read and write permissions in the repository for all scopes'
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: publish
              run: pnpm publish-npm
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
